config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #cats_url, new_cat_url, edit_cat_url, cat_url
  resources :cats do
    #cat_cat_rental_requests_url
    resources :cat_rental_requests, only: [:index]
  end

  #cat_rental_requests_url, new_cat_rental_request_url, cat_rental_request_url
  resources :cat_rental_requests, only: [:index, :show, :new, :create, :destroy]

  #approve_cat_rental_request, deny_cat_rental_request
  resources :cat_rental_requests, only: [:show] do
    member do
      get :approve
    end
    member do
      get :deny
    end
  end

  #users_url, new_user_url, edit_user_url, user_url
  resources :users do
    #user_cat_url
    resources :cats, only: [:show, :update, :edit]
    #user_requests_url
    resources :requests, only: [:index, :show, :update, :edit]
  end

  #new_session_url, session_url
  resource :session, only: [:new, :create, :destroy]

  root to: 'cats#index'
end

app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord
    STATUS = ["PENDING", "APPROVED", "DENIED"]

    validates :start_date, :end_date, :status, :cat_id, :user_id, presence: true
    validates :status, inclusion: STATUS
    validate :does_not_overlap_approved_request

    belongs_to :cat
    belongs_to :requester, class_name: :User, foreign_key: :user_id

    def overlapping_requests  
       requests = CatRentalRequest
       .where( "(start_date >= :sd AND start_date <= :ed)
               OR (end_date <= :ed AND end_date >= :sd)
               OR (start_date <= :sd AND end_date >= :ed)", {sd: self.start_date, ed: self.end_date})
       .where.not(id: self.id)
       .where(cat_id: self.cat_id)

    end

    def overlapping_approved_requests
        overlapping_requests
        .where( status: "APPROVED")
    end

    def overlapping_pending_requests
        overlapping_requests
        .where( status: "PENDING")
    end

    def does_not_overlap_approved_request
        if overlapping_approved_requests.exists?
            errors[:overlap] << "with approved request(s)."
        end
    end

    def approve!
        self.transaction do
            self.status = "APPROVED"
            self.save!
            overlapping_pending_requests
            .update_all(status: "DENIED")
        end
    end

    def deny!
        self.transaction do
            self.status = "DENIED"
            self.save!
        end  
    end

    def pending?
        self.status == "PENDING"
    end
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
    before_action :verify_cat_owner_for_request, only: [:approve, :deny]

    def index
        @cat = Cat.find_by(id: params[:cat_id])
        @owner_call = (@cat.owner == current_user)
        @cat_rental_requests = @cat.cat_rental_requests.order(:start_date)
        render :index 
    end

    def show
        @cat_rental_request = CatRentalRequest.find_by(id: params[:id])
        @cat = @cat_rental_request.cat
        
        
        if @cat_rental_request
            redirect_to user_url(current_user)   
        else
            redirect_to cat_rental_requests_url
        end
    end

    def new
        @cats = Cat.select(:id, :name).all
        @cat_rental_request = CatRentalRequest.new
        render :new
    end

    def create

        
        @cat_rental_request = CatRentalRequest.new(cat_rental_request_params)
        @cat_rental_request.user_id = current_user.id

        if @cat_rental_request.save
            flash[:notice] = 'Success!'
            redirect_to cat_rental_request_url(@cat_rental_request)
        else
            @cats = Cat.select(:id, :name).all
            flash.now[:errors] = @cat_rental_request.errors.full_messages
            render :new
        end
    end

    def approve
        @cat_rental_request = CatRentalRequest.find_by(id: params[:id])
        cat = @cat_rental_request.cat

        if @cat_rental_request.approve!
            redirect_to cat_url(cat)
        else
            flash.now[:errors] = @cat_rental_request.errors.full_messages
        end
    end

    def deny

        @cat_rental_request = CatRentalRequest.find_by(id: params[:id])
        cat = @cat_rental_request.cat

        if @cat_rental_request.deny!
            redirect_to cat_url(cat)
        else
            flash.now[:errors] = @user.errors.full_messages
        end
    end


    private

    def cat_rental_request_params
        params[:cat_rental_request].permit(:cat_id, :start_date, :end_date, :status)
    end

    def verify_cat_owner_for_request
        @cat_rental_request = CatRentalRequest.find_by(id: params[:id])
        @cat = current_user.cats.find_by(id: @cat_rental_request.cat.id)
            
        redirect_to user_url(current_user) if @cat == nil
    end 
end

app/views/cat_rental_requests/_index.html.erb
<table>
    <thead>
        <tr>
            <% if extended_list %>
                <th>Cat's Name</th>
                <th>Cat's Owner</th>
            <% end %>
            <th>Start date</th>
            <th>End date</th>
            <th>Status</th>
            <th>Requester</th>
        </tr>
    </thead>
    <% cat_rental_requests.each do |cat_r_r| %>
    <tbody>
        <tr>
            <% if extended_list %>
                <td><%= cat_r_r.cat.name %></td>
                <td><%= cat_r_r.cat.owner.username %></td>
            <% end %>
            <td><%= cat_r_r.start_date %></td>
            <td><%= cat_r_r.end_date %></td>
            <td><%= cat_r_r.status %></td>
            <td><%= cat_r_r.requester.username %>
            <td><% if (owner_call && cat_r_r.pending?) %>
                <td><%= button_to "Approve", approve_cat_rental_request_url(cat_r_r), method: :get %></td>
                <td><%= button_to "Deny", deny_cat_rental_request_url(cat_r_r), method: :get %></td>
                <% end %>
            </td>
        </tr>
    </tbody>
    <% end %>
</table>

app/views/cat_rental_requests/new.html.erb
<h1>New Cat Rental Request</h1>
<br>
<%= render 'layouts/errors' %>
<br>

<form action="<%= cat_rental_requests_url %>" method="post">
  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <label for="cat">Cat Name</label>
  <select name="cat_rental_request[cat_id]" id="cat"> 
  <option disabled selected> -- select a cat -- </option>
    <% @cats.each do |cat| %>
        <option value="<%= cat.id %>"<%= "selected" if @cat_rental_request.cat_id == cat.id %>><%= cat.name %></option>
    <% end %>
  </select>
  <br>

  <label for="rental_sd">Start Date</label>
  <input name="cat_rental_request[start_date]" value="<%= @cat_rental_request.start_date%>" id="rental_sd" type="date">
  <br>
  
  <label for="rental_ed">End Date</label>
  <input name="cat_rental_request[end_date]" value="<%= @cat_rental_request.end_date%>"id="rental_ed" type="date">
  <br>
  

  <input type="submit" value="Request">

  
</form>